"""
Document QA Endpoint for RLM.

This module provides a simple endpoint function for querying markdown documents
using the RLM framework with OpenRouter models.
"""

import os
from typing import Any

from rlm import RLM
from rlm.core.types import RLMChatCompletion
from rlm.logger.rlm_logger import RLMLogger


DEFAULT_LOG_DIR = "/tmp/rlm_logs"


def query_documents(
    documents: dict[str, str],
    query: str,
    api_key: str | None = None,
    max_iterations: int = 30,
    verbose: bool = False,
    log_dir: str | None = DEFAULT_LOG_DIR,
) -> str:
    """
    Query a set of markdown documents using RLM with Qwen3 on Cerebras.

    This endpoint takes markdown documents as context, loads them into an RLM
    environment, and uses Qwen3 (qwen/qwen3-235b-a22b-2507) via Cerebras to answer
    the query by programmatically examining and analyzing the documents.

    Args:
        documents: A dictionary mapping document names to their markdown content.
                   Example: {"readme.md": "# Title\nContent...", "guide.md": "# Guide\n..."}
        query: The question or query about the documents to answer.
        api_key: Optional OpenRouter API key. If not provided, uses the
                 OPENROUTER_API_KEY environment variable.
        max_iterations: Maximum number of RLM iterations before forcing a final answer.
                        Default is 30.
        verbose: If True, prints rich output to console showing RLM progress.
                 Default is False.
        log_dir: Directory path for RLM logs. Defaults to /tmp/rlm_logs.
                 Set to None to disable logging.

    Returns:
        The answer generated by the RLM as a string.

    Raises:
        ValueError: If documents dict is empty or query is empty.
        RuntimeError: If RLM fails to generate an answer.

    Example:
        >>> documents = {
        ...     "chapter1.md": "# Chapter 1\\nThe protagonist was born in 1985...",
        ...     "chapter2.md": "# Chapter 2\\nHe moved to New York in 2010...",
        ... }
        >>> answer = query_documents(
        ...     documents=documents,
        ...     query="When was the protagonist born and where did he move?",
        ... )
        >>> print(answer)
        The protagonist was born in 1985 and moved to New York in 2010.
    """
    # Validate inputs
    if not documents:
        raise ValueError("documents dict cannot be empty")
    if not query or not query.strip():
        raise ValueError("query cannot be empty")

    # Resolve API key
    resolved_api_key = api_key or os.getenv("OPENROUTER_API_KEY")
    if not resolved_api_key:
        raise ValueError(
            "OpenRouter API key must be provided either as 'api_key' argument "
            "or via OPENROUTER_API_KEY environment variable"
        )

    # Create RLM instance with OpenRouter backend
    logger = RLMLogger(log_dir=log_dir) if log_dir else None
    rlm = RLM(
        backend="openrouter",
        backend_kwargs={
            "model_name": "qwen/qwen3-235b-a22b-2507",
            "api_key": resolved_api_key,
            "extra_body": {
                "provider": {"order": ["Cerebras"], "allow_fallbacks": 'false'}
            },
        },
        environment="local",
        environment_kwargs={},
        max_depth=1,
        max_iterations=max_iterations,
        verbose=verbose,
        logger=logger,
    )

    # Pass documents as context and query as root_prompt
    # The documents dict will be available as `context` in the REPL environment
    # The query will be shown to the LM as the question to answer
    result: RLMChatCompletion = rlm.completion(
        prompt=documents,
        root_prompt=query,
    )

    return result.response


def query_documents_detailed(
    documents: dict[str, str],
    query: str,
    api_key: str | None = None,
    max_iterations: int = 30,
    verbose: bool = False,
    log_dir: str | None = DEFAULT_LOG_DIR,
) -> dict[str, Any]:
    """
    Query documents with detailed response including usage statistics.

    Same as query_documents but returns a detailed dict with the answer,
    usage summary, and execution time. Uses Qwen3 (qwen/qwen3-235b-a22b-2507)
    via Cerebras.

    Args:
        documents: A dictionary mapping document names to their markdown content.
        query: The question or query about the documents to answer.
        api_key: Optional OpenRouter API key.
        max_iterations: Maximum number of RLM iterations.
        verbose: If True, prints rich output to console.
        log_dir: Directory path for RLM logs. Defaults to /tmp/rlm_logs.
                 Set to None to disable logging.

    Returns:
        A dictionary containing:
        - "answer": The generated answer string
        - "model": The model used
        - "execution_time": Time taken in seconds
        - "usage": Token usage statistics per model
    """
    # Validate inputs
    if not documents:
        raise ValueError("documents dict cannot be empty")
    if not query or not query.strip():
        raise ValueError("query cannot be empty")

    # Resolve API key
    resolved_api_key = api_key or os.getenv("OPENROUTER_API_KEY")
    if not resolved_api_key:
        raise ValueError(
            "OpenRouter API key must be provided either as 'api_key' argument "
            "or via OPENROUTER_API_KEY environment variable"
        )

    # Create RLM instance with fixed model (Qwen3 on Cerebras)
    logger = RLMLogger(log_dir=log_dir) if log_dir else None
    rlm = RLM(
        backend="openrouter",
        backend_kwargs={
            "model_name": "qwen/qwen3-235b-a22b-2507",
            "api_key": resolved_api_key,
            "extra_body": {
                "provider": {"order": ["Cerebras"], "allow_fallbacks": 'false'}
            },
        },
        environment="local",
        environment_kwargs={},
        max_depth=1,
        max_iterations=max_iterations,
        verbose=verbose,
        logger=logger,
    )

    result: RLMChatCompletion = rlm.completion(
        prompt=documents,
        root_prompt=query,
    )

    return {
        "answer": result.response,
        "model": result.root_model,
        "execution_time": result.execution_time,
        "usage": result.usage_summary.to_dict(),
    }
